image: node:10.15.3-stretch
pipelines:
  default:
    - step:
        name: Pre-release build
        script:
          - apt-get update && apt-get install -y zip
          - npm install
          - npm test
